version: '3.8'

services:
  app:
    build:
      context: .  # Arahkan ke folder Dockerfile
      dockerfile: Dockerfile
    container_name: express_app
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
